addSbtPlugin("com.jsuereth"      % "sbt-pgp"       % "1.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.0")
//addSbtPlugin("com.typesafe.sbt"  % "sbt-git"       % "0.8.4")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "0.5.1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.5.0-RC2")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"  % "0.4.7")
